INSERT INTO `course` VALUES (null, '程序设计基础',null);
INSERT INTO `course` VALUES (null, '高等数学',null);
INSERT INTO `course` VALUES (null, '线性代数',null);
INSERT INTO `course` VALUES (null, '离散数学',null);
INSERT INTO `course` VALUES (null, '概率论与数理统计',null);
INSERT INTO `course` VALUES (null, '面向对象程序设计',null);
INSERT INTO `course` VALUES (null, '数据结构',null);
INSERT INTO `course` VALUES (null, '操作系统',null);
INSERT INTO `course` VALUES (null, '计算机组成原理',null);
INSERT INTO `course` VALUES (null, '计算机导论',null);
INSERT INTO `course` VALUES (null, '计算机网络',null);
INSERT INTO `course` VALUES (null, '软件工程',null);
INSERT INTO `course` VALUES (null, '软件测试方法和技术',null);
INSERT INTO `course` VALUES (null, '移动终端编程',null);
INSERT INTO `course` VALUES (null, 'WEB初级编程',null);
INSERT INTO `course` VALUES (null, 'WEB高级编程',null);
INSERT INTO `course` VALUES (null, '军事理论',null);
INSERT INTO `course` VALUES (null, '职业生涯规划',null);
INSERT INTO `course` VALUES (null, '心理健康教育',null);
INSERT INTO `course` VALUES (null, '中国近代史纲要',null);
INSERT INTO `course` VALUES (null, '毛泽东思想和中国特色社会主义理论体系概论',null);
INSERT INTO `course` VALUES (null, 'Linux基础',null);
--
INSERT INTO `major` VALUES ('1', '软件工程',null);
INSERT INTO `major` VALUES ('2', '物联网工程',null);
INSERT INTO `major` VALUES ('3', '数据科学与大数据技术',null);
INSERT INTO `major` VALUES ('4', '通信工程',null);
INSERT INTO `major` VALUES ('5', '网络工程',null);
INSERT INTO `major` VALUES ('6', '无机非金属材料工程',null);
INSERT INTO `major` VALUES ('7', '计算机科学与技术',null);
INSERT INTO `major` VALUES ('8', '金属材料工程',null);
INSERT INTO `major` VALUES ('9', '高分子材料工程',null);
INSERT INTO `major` VALUES ('10', '复合材料工程',null);
INSERT INTO `major` VALUES ('11', '应用化学',null);
INSERT INTO `major` VALUES ('12', '材料化学',null);
INSERT INTO `major` VALUES ('13', '电气工程及其自动化',null);
INSERT INTO `major` VALUES ('14', '飞行器设计与工程',null);
INSERT INTO `major` VALUES ('15', '飞行器制造工程',null);
INSERT INTO `major` VALUES ('16', '焊接技术与工程',null);
INSERT INTO `major` VALUES ('17', '信息与计算科学',null);
INSERT INTO `major` VALUES ('18', '数学与应用数学',null);
INSERT INTO `major` VALUES ('19', '光电信息科学与工程',null);
INSERT INTO `major` VALUES ('20', '生物医学工程',null);
INSERT INTO `major` VALUES ('21', '经济学',null);
INSERT INTO `major` VALUES ('22', '工商管理',null);
INSERT INTO `major` VALUES ('23', '会计学',null);
INSERT INTO `major` VALUES ('24', '电子商务',null);
INSERT INTO `major` VALUES ('25', '土木工程',null);
INSERT INTO `major` VALUES ('26', '交通工程',null);
INSERT INTO `major` VALUES ('27', '工业设计',null);
INSERT INTO `major` VALUES ('28', '动画',null);
INSERT INTO `major` VALUES ('29', '视觉传达设计',null);
INSERT INTO `major` VALUES ('30', '环境设计',null);
INSERT INTO `major` VALUES ('31', '服装与服饰设计',null);
INSERT INTO `major` VALUES ('32', '法学',null);
INSERT INTO `major` VALUES ('33', '新闻学',null);
INSERT INTO `major` VALUES ('34', '播音与主持艺术',null);
INSERT INTO `major` VALUES ('35', '音乐学',null);
INSERT INTO `major` VALUES ('36', '舞蹈学',null);
INSERT INTO `major` VALUES ('37', '表演',null);
INSERT INTO `major` VALUES ('38', '英语',null);
INSERT INTO `major` VALUES ('39', '电子信息工程',null);
--
INSERT INTO `school` VALUES (null, '清华大学', null, null,null);
INSERT INTO `school` VALUES (null, '北京大学', null, null,null);
INSERT INTO `school` VALUES (null, '中国人民大学', null, null,null);
INSERT INTO `school` VALUES (null, '上海大学', null, null,null);
INSERT INTO `school` VALUES (null, '上海第二工业大学', null, null,null);
INSERT INTO `school` VALUES (null, '上海轻工业大学', null, null,null);
INSERT INTO `school` VALUES (null, '上海应用技术大学', null, null,null);
INSERT INTO `school` VALUES (null, '南昌大学', null, null,null);
INSERT INTO `school` VALUES (null, '南昌航空大学', '丰和南大道696号', 'null',null);
INSERT INTO `school` VALUES (null, '江西财经大学', null, null,null);
INSERT INTO `school` VALUES (null, '华东交通大学', null, null,null);
INSERT INTO `school` VALUES (null, '九江学院', null, null,null);
INSERT INTO `school` VALUES (null, '华南理工大学', null, null,null);
INSERT INTO `school` VALUES (null, '广州大学', null, null,null);
INSERT INTO `school` VALUES (null, '中山大学', null, null,null);
INSERT INTO `school` VALUES (null, '深圳大学', null, null,null);
INSERT INTO `school` VALUES (null, '武汉大学', null, null,null);
INSERT INTO `school` VALUES (null, '南京大学', null, null,null);
INSERT INTO `school` VALUES (null, '河海大学', null, null,null);
INSERT INTO `school` VALUES (null, '郑州大学', null, null,null);
INSERT INTO `school` VALUES (null, '河南大学', null, null,null);
INSERT INTO `school` VALUES (null, '河南理工大学', null, null,null);
INSERT INTO `school` VALUES (null, '河南科技大学', null, null,null);
INSERT INTO `school` VALUES (null, '南阳理工大学', null, null,null);
INSERT INTO `school` VALUES (null, '濮阳工学院', null, null,null);

INSERT INTO `user` VALUES (null, 'NISHIKINOWuzhu', '321321', 'Man', '516942590@qq.com', '18079148395');
INSERT INTO `user` VALUES (null, 'wuzhu', '123123' , 'Woman', '2927962422@qq.com', '13839377962');

INSERT INTO `book` VALUES (null, 'Android移动应用开发教程', '清华大学出版社', '978-7-302-49105-7', '祝永志', '', 49, 'TJ', 'Admin', 0, 'images/default.png',0);
INSERT INTO `book` VALUES (null, '软件测试方法和技术', '清华大学出版社', '978-7-302-37031-4', '朱少民', '', 44.5, 'TJ', 'Admin', 0, 'images/20191231170610.png',0);
